/* Memory Card v0.16 — Game Identity, Backlog, Collections, Rotations, Social */
(() => {
  const VIEW_KEY='memory-card-games-view-v2';
  const ROTATION_MODES=['classic','balance','random'];
  const ACCENTS=['memory','ps2','gameboy','dreamcast','xbox','famicom','vita','oled','sunset','arcade','glacier','mono'];
  state.collectionId='';state.franchiseName='';state.gameDetailId='';state.friendCompare=false;

  Object.assign(DEFAULT_SETTINGS,{rotationHandheldMode:'classic',rotationDesktopMode:'classic',accentTheme:'memory',collections:[]});
  const baseMigrateV16=migrateSettings;
  migrateSettings=function(raw={}){const out=baseMigrateV16(raw);out.rotationHandheldMode=ROTATION_MODES.includes(raw.rotationHandheldMode)?raw.rotationHandheldMode:'classic';out.rotationDesktopMode=ROTATION_MODES.includes(raw.rotationDesktopMode)?raw.rotationDesktopMode:'classic';out.accentTheme=ACCENTS.includes(raw.accentTheme)?raw.accentTheme:'memory';out.collections=Array.isArray(raw.collections)?raw.collections.map(c=>({id:String(c.id||''),name:String(c.name||'Коллекция').trim().slice(0,60)||'Коллекция',icon:String(c.icon||'💾').slice(0,4),gameIds:[...new Set(Array.isArray(c.gameIds)?c.gameIds.map(String):[])],createdAt:String(c.createdAt||nowIso())})).filter(c=>c.id):[];return out;};
  state.settings=migrateSettings(state.settings||{});

  const baseLiveGamesV16=liveGames;
  liveGames=function(){return baseLiveGamesV16().filter(g=>g.status!=='backlog');};
  const backlogGames=()=>state.games.filter(g=>g&&!g.deletedAt&&g.status==='backlog').map(migrateGame);
  const collections=()=>Array.isArray(state.settings.collections)?state.settings.collections:[];
  const gameById=id=>state.games.find(g=>g.id===id&&!g.deletedAt)||null;
  const norm=v=>String(v||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9а-яё]+/gi,' ').replace(/\s+/g,' ').trim();
  const modeKey=g=>g==='desktop'?'rotationDesktopMode':'rotationHandheldMode';
  const accent=()=>ACCENTS.includes(state.settings.accentTheme)?state.settings.accentTheme:'memory';
  function applyAccent(){document.documentElement.dataset.mcAccent=accent();document.documentElement.classList.toggle('mc-oled-accent',accent()==='oled');}
  applyAccent();

  const baseSyncV16=syncableSettings;
  syncableSettings=function(){return {...baseSyncV16(),rotationHandheldMode:state.settings.rotationHandheldMode,rotationDesktopMode:state.settings.rotationDesktopMode,accentTheme:state.settings.accentTheme,collections:collections().map(c=>({...c,gameIds:[...c.gameIds]}))};};
  const baseMergeV16=mergeClientSettings;
  mergeClientSettings=function(local,remote){const out=baseMergeV16(local,remote),remoteWins=String(remote?.settingsUpdatedAt||'')>=String(local?.settingsUpdatedAt||'');const src=remoteWins?(remote||{}):(local||{});out.rotationHandheldMode=ROTATION_MODES.includes(src.rotationHandheldMode)?src.rotationHandheldMode:(out.rotationHandheldMode||'classic');out.rotationDesktopMode=ROTATION_MODES.includes(src.rotationDesktopMode)?src.rotationDesktopMode:(out.rotationDesktopMode||'classic');out.accentTheme=ACCENTS.includes(src.accentTheme)?src.accentTheme:(out.accentTheme||'memory');out.collections=Array.isArray(src.collections)?migrateSettings({collections:src.collections}).collections:(out.collections||[]);return out;};

  const baseSaveSettingsV16=saveSettings;
  saveSettings=async function(silent=false){const hh=document.querySelector('#rotationHandheldMode'),dd=document.querySelector('#rotationDesktopMode'),ac=document.querySelector('#accentTheme');const desired={hh:hh?.value,dd:dd?.value,ac:ac?.value};await baseSaveSettingsV16(true);if(ROTATION_MODES.includes(desired.hh))state.settings.rotationHandheldMode=desired.hh;if(ROTATION_MODES.includes(desired.dd))state.settings.rotationDesktopMode=desired.dd;if(ACCENTS.includes(desired.ac))state.settings.accentTheme=desired.ac;state.settings.settingsUpdatedAt=nowIso();await persist();applyAccent();scheduleAutoSync();if(!silent)setToast('Настройки сохранены');render();};

  const baseNextV16=nextPlatformAfter;
  nextPlatformAfter=function(id,group){const mode=state.settings[modeKey(group)]||'classic',r=rotationFor(group);if(mode==='classic'||r.length<2)return baseNextV16(id,group);const candidates=r.filter(x=>x!==id);if(mode==='random')return candidates[Math.floor(Math.random()*candidates.length)]||id;const activity={};r.forEach(x=>activity[x]='');liveGames().filter(g=>r.includes(g.platform)).forEach(g=>{const d=String(g.updatedAt||g.addedAt||'');if(d>String(activity[g.platform]||''))activity[g.platform]=d;});return candidates.sort((a,b)=>String(activity[a]||'').localeCompare(String(activity[b]||'')))[0]||baseNextV16(id,group);};

  const baseRotationEditorV16=rotationEditor;
  rotationEditor=function(group){let html=baseRotationEditorV16(group);const current=state.settings[modeKey(group)]||'classic';const block=`<div class="v16-rotation-mode"><div class="v16-setting-title"><div><b>Режим ротации</b><small>Определяет, какая приставка станет следующей после завершения этапа.</small></div><button type="button" class="v16-info" data-v16-help="rotation-${group}" aria-label="Как работают режимы">?</button></div><select id="rotation${group==='desktop'?'Desktop':'Handheld'}Mode" data-v16-rotation-mode="${group}"><option value="classic" ${current==='classic'?'selected':''}>Классическая</option><option value="balance" ${current==='balance'?'selected':''}>Баланс</option><option value="random" ${current==='random'?'selected':''}>Случайная</option></select><div class="v16-helpbox" data-v16-helpbox="rotation-${group}" hidden><b>Классическая</b> — строго по заданному порядку.<br><b>Баланс</b> — следующей становится система, на которой ты дольше всего не играл.<br><b>Случайная</b> — следующая система выбирается случайно из очереди, кроме текущей.</div></div>`;return html.replace(/<\/section>\s*$/,block+'</section>');};

  const baseRenderSettingsV16=renderSettings;
  renderSettings=function(){const html=baseRenderSettingsV16();const themeNames={memory:'Memory Purple',ps2:'PS2 Blue',gameboy:'Game Boy Green',dreamcast:'Dreamcast Orange',xbox:'Xbox Green',famicom:'Famicom Red',vita:'Vita Aqua',oled:'OLED Black',sunset:'Sunset',arcade:'Arcade Neon',glacier:'Glacier',mono:'Monochrome'};const panel=`<section class="panel v16-accent-panel"><div class="settings-panel-head"><div><h3>Акцент интерфейса</h3><p class="status-line">Цветовая атмосфера Memory Card. Не меняет данные и тему светлая/тёмная.</p></div></div><div class="field"><label>Стиль</label><select id="accentTheme">${ACCENTS.map(x=>`<option value="${x}" ${accent()===x?'selected':''}>${themeNames[x]}</option>`).join('')}</select></div><div class="v16-theme-swatches">${ACCENTS.map(x=>`<button type="button" class="v16-swatch ${accent()===x?'active':''}" data-v16-accent="${x}" title="${themeNames[x]}"><i></i></button>`).join('')}</div></section>`;return html+panel;};

  const baseHomeV16=renderHome;
  renderHome=function(){const playing=[...liveGames().filter(g=>g.status==='playing')].sort((a,b)=>String(b.updatedAt||b.addedAt||'').localeCompare(String(a.updatedAt||a.addedAt||''))),current=playing[0],last=[...liveGames().filter(g=>g.status==='completed')].sort((a,b)=>String(b.updatedAt||b.addedAt||'').localeCompare(String(a.updatedAt||a.addedAt||'')))[0];const nextH=mcRotationEnabled('handheld')?currentPlatformFor('handheld'):'';const nextD=mcRotationEnabled('desktop')?currentPlatformFor('desktop'):'';const hero=current?`<section class="v16-home-hero platform-bg-${String(current.platform).toLowerCase()}" ${current.coverUrl?`style="--hero-image:url('${esc(current.coverUrl)}')"`:''}><div class="v16-hero-cover">${coverMarkup(current,'v16-hero-art')}</div><div class="v16-hero-copy"><span class="v16-eyebrow">Сейчас играешь</span><h2>${esc(current.title)}</h2><div class="v16-badge-row"><span>${esc(platform(current.platform).abbr)}</span>${current.releaseYear?`<span>${esc(current.releaseYear)}</span>`:''}${current.genre?`<span>${esc(current.genre)}</span>`:''}</div>${current.notes?`<p>${esc(current.notes)}</p>`:''}<button class="primary" data-v16-game-detail="${esc(current.id)}">Открыть игру</button></div><div class="v16-hero-side"><div><small>Ротация</small><b>${[nextH,nextD].filter(Boolean).map(x=>platform(x).abbr).join(' · ')||'Свободная игра'}</b></div>${last?`<button data-v16-game-detail="${esc(last.id)}"><small>Последнее прохождение</small><b>${esc(last.title)}</b><span>${last.rating?`${last.rating}/10`:platform(last.platform).abbr}</span></button>`:''}</div></section>`:`<section class="v16-home-hero empty-hero"><div><span class="v16-eyebrow">Memory Card</span><h2>Выбери следующую игру</h2><p>Начни игру из Backlog или добавь текущую через «+ Прошёл игру».</p><button class="primary" data-nav="backlog">Открыть Backlog</button></div></section>`;return hero+baseHomeV16();};

  function gameMini(g){return `<button class="v16-mini-game" data-v16-game-detail="${esc(g.id)}">${coverMarkup(g,'mini-cover')}<span><b>${esc(g.title)}</b><small>${esc(platform(g.platform).abbr)}${g.rating?` · ${g.rating}/10`:''}</small></span></button>`;}
  function renderBacklog(){const games=backlogGames();return `<div class="section-head"><div><h2>Backlog</h2><p>Игры на потом. Они не входят в библиотеку, статистику и общий список, пока ты не начнёшь прохождение.</p></div></div><section class="panel v16-backlog-add"><h3>Добавить в Backlog</h3><form id="v16BacklogForm" class="v16-backlog-form"><input name="title" required maxlength="160" placeholder="Название игры"><select name="platform">${mcOwnedPlatforms().map(id=>`<option value="${id}">${esc(platform(id).name)}</option>`).join('')}</select><input name="releaseYear" maxlength="4" inputmode="numeric" placeholder="Год"><input name="genre" maxlength="80" placeholder="Жанр"><input name="franchise" maxlength="100" placeholder="Франшиза"><textarea name="notes" rows="2" maxlength="1000" placeholder="Почему хочу пройти / заметка"></textarea><button class="primary" type="submit">+ В Backlog</button></form></section><section class="panel"><div class="section-head"><div><h3>Очередь</h3><p>${games.length} ${games.length===1?'игра':'игр'}</p></div></div>${games.length?`<div class="v16-backlog-grid">${games.map(g=>`<article class="v16-backlog-card">${coverMarkup(g,'v16-backlog-cover')}<div><span class="v16-platform-pill">${esc(platform(g.platform).abbr)}</span><h3>${esc(g.title)}</h3><p>${esc(g.notes||g.genre||'Без заметки')}</p><div class="v16-card-actions"><button class="primary compact" data-v16-backlog-start="${esc(g.id)}">Начинаю проходить</button><button class="ghost compact" data-v16-backlog-remove="${esc(g.id)}">Удалить</button></div></div></article>`).join('')}</div>`:'<div class="empty">Backlog пуст. Добавь сюда игры, которые хочешь когда-нибудь начать.</div>'}</section>`;}

  function renderCollections(){const all=collections();if(state.collectionId){const c=all.find(x=>x.id===state.collectionId);if(!c){state.collectionId='';return renderCollections();}const games=(c.gameIds||[]).map(gameById).filter(Boolean).filter(g=>g.status!=='backlog');return `<div class="section-head"><div><button class="ghost compact" data-v16-collection-back>← Коллекции</button><h2>${esc(c.icon)} ${esc(c.name)}</h2><p>${games.length} игр</p></div><button class="danger compact" data-v16-collection-delete="${esc(c.id)}">Удалить коллекцию</button></div><section class="panel">${games.length?`<div class="v16-collection-grid">${games.map(gameMini).join('')}</div>`:'<div class="empty">В коллекции пока нет игр. Добавляй их со страницы игры.</div>'}</section>`;}return `<div class="section-head"><div><h2>Коллекции</h2><p>Свои тематические полки: любимое, хорроры, игры детства, на осень — как угодно.</p></div></div><section class="panel"><form id="v16CollectionForm" class="v16-collection-form"><input name="icon" maxlength="4" value="💾" aria-label="Иконка"><input name="name" required maxlength="60" placeholder="Название коллекции"><button class="primary" type="submit">Создать коллекцию</button></form></section><div class="v16-collection-cards">${all.map(c=>{const gs=(c.gameIds||[]).map(gameById).filter(Boolean).filter(g=>g.status!=='backlog');return `<button class="v16-collection-card" data-v16-collection-open="${esc(c.id)}"><span class="v16-collection-icon">${esc(c.icon)}</span><div><h3>${esc(c.name)}</h3><p>${gs.length} игр</p><div class="v16-cover-stack">${gs.slice(0,4).map(g=>g.coverUrl?`<img src="${esc(g.coverUrl)}" alt="">`:`<i>${esc(platform(g.platform).abbr)}</i>`).join('')}</div></div></button>`;}).join('')||'<section class="panel empty">Создай первую коллекцию.</section>'}</div>`;}

  function renderGameDetail(){const g=gameById(state.gameDetailId);if(!g||g.status==='backlog'){state.gameDetailId='';return renderHome();}const related=g.franchise?liveGames().filter(x=>x.id!==g.id&&norm(x.franchise)===norm(g.franchise)):[];const ownCollections=collections().filter(c=>(c.gameIds||[]).includes(g.id));return `<div class="v16-detail platform-bg-${String(g.platform).toLowerCase()}" ${g.coverUrl?`style="--hero-image:url('${esc(g.coverUrl)}')"`:''}><div class="v16-detail-bg"></div><button class="ghost compact v16-detail-back" data-v16-detail-back>← Назад</button><div class="v16-detail-hero">${coverMarkup(g,'v16-detail-cover')}<div class="v16-detail-copy"><div class="v16-badge-row"><span>${esc(platform(g.platform).name)}</span>${g.releaseYear?`<span>${esc(g.releaseYear)}</span>`:''}<span>${g.status==='playing'?'Сейчас играю':'Пройдено'}</span></div><h1>${esc(g.title)}</h1>${g.franchise?`<button class="v16-franchise-link" data-v16-franchise="${esc(g.franchise)}">${esc(g.franchise)}</button>`:''}<div class="v16-detail-rating">${g.rating?`<strong>${esc(g.rating)}</strong><span>/10<br>${ratingStars(g.rating)}</span>`:'<strong>—</strong><span>без оценки</span>'}</div><div class="v16-detail-actions"><button class="primary" data-v16-edit="${esc(g.id)}">Редактировать</button></div></div></div></div><div class="v16-detail-grid"><section class="panel"><h3>Моя запись</h3><p class="v16-notes">${g.notes?esc(g.notes):'<span class="muted">Комментарий не добавлен.</span>'}</p><div class="v16-meta-list"><div><small>Жанр</small><b>${esc(g.genre||'—')}</b></div><div><small>Добавлено</small><b>${esc(String(g.addedAt||'').slice(0,10)||'—')}</b></div><div><small>Последнее изменение</small><b>${esc(String(g.updatedAt||'').slice(0,10)||'—')}</b></div><div><small>Перепрохождения</small><b>${Number(g.replay||0)}</b></div></div></section><section class="panel"><h3>Коллекции</h3>${collections().length?`<div class="v16-collection-add"><select data-v16-collection-select="${esc(g.id)}"><option value="">Выбери коллекцию</option>${collections().filter(c=>!(c.gameIds||[]).includes(g.id)).map(c=>`<option value="${esc(c.id)}">${esc(c.icon)} ${esc(c.name)}</option>`).join('')}</select><button class="secondary" data-v16-collection-add="${esc(g.id)}">Добавить</button></div>`:'<p class="muted">Сначала создай коллекцию.</p>'}<div class="v16-chip-list">${ownCollections.map(c=>`<span>${esc(c.icon)} ${esc(c.name)} <button data-v16-collection-remove-game="${esc(c.id)}" data-game-id="${esc(g.id)}">×</button></span>`).join('')||'<span class="muted">Пока ни в одной</span>'}</div></section>${related.length?`<section class="panel v16-related"><div class="section-head"><div><h3>Ещё из франшизы</h3><p>${related.length} в библиотеке</p></div><button class="ghost compact" data-v16-franchise="${esc(g.franchise)}">Открыть франшизу</button></div><div class="v16-collection-grid">${related.slice(0,8).map(gameMini).join('')}</div></section>`:''}</div>`;}

  function renderFranchise(){const name=state.franchiseName,games=liveGames().filter(g=>norm(g.franchise)===norm(name)),completed=games.filter(g=>g.status==='completed'),rated=completed.map(g=>Number(g.rating)).filter(Boolean),playing=games.filter(g=>g.status==='playing'),avg=rated.length?(rated.reduce((a,b)=>a+b,0)/rated.length).toFixed(1):'—';return `<div class="section-head"><div><button class="ghost compact" data-v16-franchise-back>← Назад</button><h2>${esc(name)}</h2><p>Страница франшизы в твоей библиотеке.</p></div></div><div class="stats"><div class="stat-card"><div class="stat-value">${games.length}</div><div class="stat-label">Всего в библиотеке</div></div><div class="stat-card"><div class="stat-value">${completed.length}</div><div class="stat-label">Пройдено</div></div><div class="stat-card"><div class="stat-value">${playing.length}</div><div class="stat-label">Сейчас играю</div></div><div class="stat-card"><div class="stat-value">${avg}</div><div class="stat-label">Средняя оценка</div></div></div><section class="panel"><div class="v16-franchise-progress"><div><span>Пройдено в твоей библиотеке</span><b>${completed.length}/${games.length}</b></div><i><b style="width:${games.length?Math.round(completed.length/games.length*100):0}%"></b></i></div><div class="v16-collection-grid">${games.sort((a,b)=>Number(a.releaseYear||9999)-Number(b.releaseYear||9999)).map(gameMini).join('')}</div></section>`;}

  function renderAchievements(){const items=MemoryCardAchievements?.evaluate(state.games,state.settings)||[],unlocked=items.filter(x=>x.unlocked).length;return `<div class="section-head"><div><h2>Достижения</h2><p>Внутренние достижения Memory Card. Никакого playtime — только твой игровой архив.</p></div><div class="v16-ach-progress"><b>${unlocked}/100</b><span>открыто</span></div></div><div class="v16-ach-grid">${items.map((a,i)=>{const hidden=a.hidden&&!a.unlocked;return `<article class="v16-ach ${a.unlocked?'unlocked':''} ${hidden?'secret':''}"><div class="v16-ach-icon">${a.unlocked?'🏆':hidden?'?':'◇'}</div><div><small>#${String(i+1).padStart(3,'0')}${a.hidden?' · скрытое':''}</small><h3>${hidden?'Скрытое достижение':esc(a.name)}</h3><p>${hidden?'Условие откроется после получения.':esc(a.description)}</p></div></article>`;}).join('')}</div>`;}

  function profileStats(games,settings={}){const live=games.filter(g=>!g.deletedAt&&g.status!=='backlog'),completed=live.filter(g=>g.status==='completed'),playing=live.filter(g=>g.status==='playing'),rated=completed.map(g=>Number(g.rating)).filter(Boolean),ach=MemoryCardAchievements?.evaluate(games,settings).filter(x=>x.unlocked).length||0;return{completed:completed.length,playing:playing.length,average:rated.length?(rated.reduce((a,b)=>a+b,0)/rated.length).toFixed(1):'—',tens:completed.filter(g=>Number(g.rating)===10).length,ach};}
  function renderFriendProfileV16(){const fp=state.friendProfile,p=fp.profile||{},games=(fp.games||[]).map(migrateGame).filter(g=>g.status!=='backlog'),st=profileStats(games,p),playing=games.filter(g=>g.status==='playing'),completed=games.filter(g=>g.status==='completed').sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||''))),owned=new Set(p.ownedPlatforms||[]);if(state.friendCompare)return renderFriendCompareV16(p,games);return `<div class="section-head"><div><h2>${esc(p.displayName||'Игрок')}</h2><p class="memory-id">${esc(p.userId||'')}</p></div><button class="secondary" data-action="friend-back">← К друзьям</button></div><section class="v16-friend-hero"><div class="social-avatar xl">${esc((p.displayName||'И')[0].toUpperCase())}</div><div><span class="v16-eyebrow">Memory Card Profile</span><h2>${esc(p.displayName||'Игрок')}</h2><p>${esc(p.userId||'')}</p><div class="v16-badge-row">${PLATFORMS.filter(x=>owned.has(x.id)).slice(0,8).map(x=>`<span>${esc(x.abbr)}</span>`).join('')}</div></div><div class="v16-friend-actions"><button class="primary" data-v16-friend-compare>Сравнить профили</button><button class="danger compact" data-action="friend-remove" data-friend-id="${esc(p.userId||'')}">Удалить из друзей</button></div></section><div class="stats"><div class="stat-card"><div class="stat-value">${st.completed}</div><div class="stat-label">Игр пройдено</div></div><div class="stat-card"><div class="stat-value">${st.average}</div><div class="stat-label">Средняя оценка</div></div><div class="stat-card"><div class="stat-value">${st.playing}</div><div class="stat-label">Сейчас играет</div></div><div class="stat-card"><div class="stat-value">${st.ach}</div><div class="stat-label">Достижений</div></div></div>${playing.length?`<section class="panel"><h3>Сейчас играет</h3><div class="v16-collection-grid">${playing.map(g=>`<div class="v16-friend-game">${coverMarkup(g,'mini-cover')}<div><b>${esc(g.title)}</b><small>${esc(platform(g.platform).abbr)}</small></div></div>`).join('')}</div></section>`:''}<section class="panel"><div class="section-head"><div><h3>Последние прохождения</h3><p>${completed.length} всего</p></div></div><div class="v16-collection-grid">${completed.slice(0,16).map(g=>`<div class="v16-friend-game">${coverMarkup(g,'mini-cover')}<div><b>${esc(g.title)}</b><small>${esc(platform(g.platform).abbr)}${g.rating?` · ${g.rating}/10`:''}</small></div></div>`).join('')||'<div class="empty">Нет завершённых игр.</div>'}</div></section>`;}
  function renderFriendCompareV16(p,friendGames){const mine=liveGames(),theirs=friendGames.filter(g=>g.status!=='backlog'),myMap=new Map(mine.map(g=>[norm(g.title),g])),common=theirs.filter(g=>myMap.has(norm(g.title))),ratedCommon=common.map(g=>[myMap.get(norm(g.title)),g]).filter(([a,b])=>Number(a.rating)&&Number(b.rating)).sort((x,y)=>Math.abs(Number(y[0].rating)-Number(y[1].rating))-Math.abs(Number(x[0].rating)-Number(x[1].rating))),gap=ratedCommon[0],ms=profileStats(mine,state.settings),fs=profileStats(theirs,p);const fav=arr=>{const m={};arr.filter(g=>g.status==='completed').forEach(g=>m[g.platform]=(m[g.platform]||0)+1);return Object.entries(m).sort((a,b)=>b[1]-a[1])[0]?.[0]||'';};return `<div class="section-head"><div><button class="ghost compact" data-v16-friend-compare-back>← Профиль</button><h2>Сравнение с ${esc(p.displayName||'другом')}</h2><p>${common.length} общих игр</p></div></div><section class="v16-versus"><div><span>Ты</span><strong>${esc(state.settings.profileName||'Игрок')}</strong><b>${ms.completed}</b><small>пройдено</small></div><i>VS</i><div><span>Друг</span><strong>${esc(p.displayName||'Игрок')}</strong><b>${fs.completed}</b><small>пройдено</small></div></section><div class="v16-compare-grid"><section class="panel"><h3>Средняя оценка</h3><div class="v16-big-compare"><b>${ms.average}</b><span>vs</span><b>${fs.average}</b></div></section><section class="panel"><h3>Любимая платформа</h3><div class="v16-big-compare"><b>${fav(mine)?esc(platform(fav(mine)).abbr):'—'}</b><span>vs</span><b>${fav(theirs)?esc(platform(fav(theirs)).abbr):'—'}</b></div></section><section class="panel"><h3>Достижения</h3><div class="v16-big-compare"><b>${ms.ach}</b><span>vs</span><b>${fs.ach}</b></div></section>${gap?`<section class="panel"><h3>Самое большое расхождение</h3><p><b>${esc(gap[0].title)}</b></p><div class="v16-big-compare"><b>${gap[0].rating}/10</b><span>vs</span><b>${gap[1].rating}/10</b></div></section>`:''}</div><section class="panel"><div class="section-head"><div><h3>Общие игры</h3><p>${common.length}</p></div></div><div class="v16-common-games">${common.slice(0,40).map(g=>{const me=myMap.get(norm(g.title));return `<div><b>${esc(g.title)}</b><span>${me.rating?`${me.rating}/10`:'—'} · ${g.rating?`${g.rating}/10`:'—'}</span></div>`;}).join('')||'<div class="empty">Пока нет общих игр.</div>'}</div></section>`;}

  const baseOpenGameV16=openGame;
  openGame=function(id){const g=gameById(id);if(g&&g.status!=='backlog'){state.gameDetailId=id;state.view='gameDetail';state.modal=null;render();window.scrollTo({top:0,behavior:state.settings.reducedMotion?'auto':'smooth'});}else baseOpenGameV16(id);};

  navButtons=function(){const items=[['home','Главная'],['playing','Сейчас играю'],['games','Игры'],['backlog','Backlog'],['collections','Коллекции'],['timeline','Лог'],['stats','Статистика'],['achievements','Достижения'],['friends','Друзья'],['settings','Настройки']];return items.map(([v,label])=>`<button data-nav="${v}" class="${state.view===v?'active':''}">${label}${v==='friends'&&state.social?.incoming?.length?`<span class="nav-badge">${state.social.incoming.length}</span>`:''}</button>`).join('');};
  const baseViewV16=renderView;
  renderView=function(){if(state.view==='backlog')return renderBacklog();if(state.view==='collections')return renderCollections();if(state.view==='achievements')return renderAchievements();if(state.view==='gameDetail')return renderGameDetail();if(state.view==='franchise')return renderFranchise();if(state.view==='friends'&&state.friendProfile&&!state.friendProfile.loading&&!state.friendProfile.error)return renderFriendProfileV16();return baseViewV16();};
  const baseNavigateV16=navigate;
  navigate=function(view){state.collectionId='';state.franchiseName='';state.gameDetailId='';state.friendCompare=false;baseNavigateV16(view);};

  async function saveBacklog(form){const fd=new FormData(form),title=String(fd.get('title')||'').trim(),pid=String(fd.get('platform')||'');if(!title||!pid)return;const now=nowIso(),g=migrateGame({id:crypto.randomUUID?crypto.randomUUID():`b-${Date.now()}-${Math.random().toString(16).slice(2)}`,title,platform:pid,status:'backlog',releaseYear:String(fd.get('releaseYear')||''),genre:String(fd.get('genre')||''),franchise:String(fd.get('franchise')||''),notes:String(fd.get('notes')||''),rating:'',replay:0,coverUrl:'',addedAt:now,updatedAt:now});state.games.push(g);await persist();render();scheduleAutoSync();setToast('Добавлено в Backlog');try{const c=await fetchCoverForGame(g.title,g.releaseYear,g.platform);if(c?.url){g.coverUrl=c.url;g.coverSource=c.source||'';g.updatedAt=nowIso();await persist();render();scheduleAutoSync();}}catch(_){} }
  async function startBacklog(id){const g=gameById(id);if(!g||g.status!=='backlog')return;g.status='playing';g.updatedAt=nowIso();g.rating='';await persist();scheduleAutoSync();setToast(`${g.title}: прохождение начато`);navigate('playing');}
  async function removeBacklog(id){const g=gameById(id);if(!g||g.status!=='backlog')return;if(!confirm(`Удалить «${g.title}» из Backlog?`))return;g.deletedAt=nowIso();g.updatedAt=g.deletedAt;await persist();scheduleAutoSync();render();}
  async function createCollection(form){const fd=new FormData(form),name=String(fd.get('name')||'').trim(),icon=String(fd.get('icon')||'💾').trim()||'💾';if(!name)return;state.settings.collections=[...collections(),{id:crypto.randomUUID?crypto.randomUUID():`c-${Date.now()}`,name:name.slice(0,60),icon:icon.slice(0,4),gameIds:[],createdAt:nowIso()}];state.settings.settingsUpdatedAt=nowIso();await persist();scheduleAutoSync();render();setToast('Коллекция создана');}
  async function addToCollection(gameId,collectionId){if(!collectionId)return;const c=collections().find(x=>x.id===collectionId);if(!c)return;c.gameIds=[...new Set([...(c.gameIds||[]),gameId])];state.settings.settingsUpdatedAt=nowIso();await persist();scheduleAutoSync();render();setToast('Добавлено в коллекцию');}
  async function removeFromCollection(gameId,collectionId){const c=collections().find(x=>x.id===collectionId);if(!c)return;c.gameIds=(c.gameIds||[]).filter(x=>x!==gameId);state.settings.settingsUpdatedAt=nowIso();await persist();scheduleAutoSync();render();}
  async function deleteCollection(id){const c=collections().find(x=>x.id===id);if(!c||!confirm(`Удалить коллекцию «${c.name}»? Игры останутся в библиотеке.`))return;state.settings.collections=collections().filter(x=>x.id!==id);state.settings.settingsUpdatedAt=nowIso();state.collectionId='';await persist();scheduleAutoSync();render();}

  function enhanceLibrary(){const select=document.querySelector('#gamesView');if(select&&!select.querySelector('option[value="shelf"]'))select.insertAdjacentHTML('beforeend','<option value="shelf">Полка</option>');const raw=(()=>{try{return localStorage.getItem(VIEW_KEY)||'4';}catch(_){return'4';}})(),grid=document.querySelector('.game-grid');if(select&&raw==='shelf')select.value='shelf';if(grid){grid.classList.toggle('v16-shelf',raw==='shelf');if(raw==='shelf')grid.classList.remove('v14-view-1','v14-view-4','v14-view-6','v14-view-8');}
    document.querySelectorAll('.game-card[data-game]').forEach(card=>{if(card.querySelector('.v16-cover-badges'))return;const g=gameById(card.dataset.game),cover=card.querySelector('.cover');if(!g||!cover)return;cover.insertAdjacentHTML('beforeend',`<div class="v16-cover-badges"><span>${esc(platform(g.platform).abbr)}</span>${g.rating?`<span>${esc(g.rating)}/10</span>`:''}${g.releaseYear?`<span>${esc(g.releaseYear)}</span>`:''}</div>`);});
    document.querySelectorAll('.franchise-chip').forEach(x=>x.classList.add('v16-clickable-franchise'));document.querySelectorAll('.franchise-stat').forEach(x=>x.classList.add('v16-clickable-franchise'));}
  let queued=false;function enhance(){applyAccent();enhanceLibrary();const appearance=document.querySelector('.appearance-extra-grid');if(appearance&&!appearance.querySelector('.v16-inline-accent')){const e=document.createElement('div');e.className='field v16-inline-accent';e.innerHTML=`<label>Акцент</label><span>${esc(accent())}</span>`;appearance.appendChild(e);}}
  function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;enhance();});}
  const app=document.querySelector('#app');if(app)new MutationObserver(schedule).observe(app,{childList:true,subtree:true});schedule();

  document.addEventListener('submit',e=>{if(e.target?.id==='v16BacklogForm'){e.preventDefault();saveBacklog(e.target);}if(e.target?.id==='v16CollectionForm'){e.preventDefault();createCollection(e.target);}});
  document.addEventListener('change',e=>{if(e.target?.id==='gamesView'){try{localStorage.setItem(VIEW_KEY,e.target.value);}catch(_){}setTimeout(enhanceLibrary,0);}if(e.target?.matches('[data-v16-rotation-mode]')){const group=e.target.dataset.v16RotationMode;state.settings[modeKey(group)]=e.target.value;state.settings.settingsUpdatedAt=nowIso();persist().then(()=>scheduleAutoSync());}});
  document.addEventListener('click',e=>{const el=e.target instanceof Element?e.target.closest('[data-v16-game-detail],[data-v16-backlog-start],[data-v16-backlog-remove],[data-v16-collection-open],[data-v16-collection-back],[data-v16-collection-delete],[data-v16-collection-add],[data-v16-collection-remove-game],[data-v16-edit],[data-v16-detail-back],[data-v16-franchise],[data-v16-franchise-back],[data-v16-help],[data-v16-accent],[data-v16-friend-compare],[data-v16-friend-compare-back],.v16-clickable-franchise'):null;if(!el)return;
    if(el.dataset.v16GameDetail){openGame(el.dataset.v16GameDetail);return;}if(el.dataset.v16BacklogStart){startBacklog(el.dataset.v16BacklogStart);return;}if(el.dataset.v16BacklogRemove){removeBacklog(el.dataset.v16BacklogRemove);return;}if(el.hasAttribute('data-v16-collection-back')){state.collectionId='';render();return;}if(el.dataset.v16CollectionOpen){state.collectionId=el.dataset.v16CollectionOpen;render();return;}if(el.dataset.v16CollectionDelete){deleteCollection(el.dataset.v16CollectionDelete);return;}if(el.dataset.v16CollectionAdd){const s=document.querySelector(`[data-v16-collection-select="${CSS.escape(el.dataset.v16CollectionAdd)}"]`);addToCollection(el.dataset.v16CollectionAdd,s?.value||'');return;}if(el.dataset.v16CollectionRemoveGame){removeFromCollection(el.dataset.gameId,el.dataset.v16CollectionRemoveGame);return;}if(el.dataset.v16Edit){baseOpenGameV16(el.dataset.v16Edit);return;}if(el.hasAttribute('data-v16-detail-back')){navigate('games');return;}if(el.dataset.v16Franchise){state.franchiseName=el.dataset.v16Franchise;state.view='franchise';render();return;}if(el.hasAttribute('data-v16-franchise-back')){navigate('stats');return;}if(el.classList.contains('v16-clickable-franchise')){const name=el.classList.contains('franchise-chip')?el.textContent.trim():el.querySelector('span')?.textContent?.trim();if(name){state.franchiseName=name;state.view='franchise';render();}return;}if(el.dataset.v16Help){const b=document.querySelector(`[data-v16-helpbox="${el.dataset.v16Help}"]`);if(b)b.hidden=!b.hidden;return;}if(el.dataset.v16Accent){state.settings.accentTheme=el.dataset.v16Accent;state.settings.settingsUpdatedAt=nowIso();persist().then(()=>{applyAccent();render();scheduleAutoSync();});return;}if(el.hasAttribute('data-v16-friend-compare')){state.friendCompare=true;render();return;}if(el.hasAttribute('data-v16-friend-compare-back')){state.friendCompare=false;render();return;}
  });
})();